version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: ../Dockerfile.frontend
    image: frontend_custom
    container_name: opgranel_frontend
    ports:
      - "3008:3008"
    environment:
      REACT_APP_SERVER: http://31.97.20.141:3009
      PORT: 3008
      TZ: America/Sao_Paulo
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: ../Dockerfile.backend
    image: backend_custom
    container_name: opgranel_backend
    working_dir: /app
    volumes:
      - ./server/Files/Notas_Fiscais:/app/server/Files/Notas_Fiscais
    command: node index.js
    ports:
      - "3009:3009"
    environment:
      DB_HOST: 31.97.20.141
      DB_PORT: 3306
      DB_USER: ogdev
      DB_PASS: R0dr!m@rR##T
      DB_NAME: operacaogranel
      PORT: 3009
      TZ: America/Sao_Paulo
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: opgranel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: R0dr!m@rR##T
      MYSQL_DATABASE: operacaogranel
      MYSQL_USER: ogdev
      MYSQL_PASSWORD: R0dr!m@rR##T
      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: 1
      TZ: America/Sao_Paulo
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/init:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    restart: always

networks:
  default:
    name: app-network
