ALTER TABLE `OPERACAO`
  ADD COLUMN `TICKET_NAVIO` varchar(64) DEFAULT NULL
  COMMENT 'Ticket/comando do WhatsApp para identificar o navio'
  AFTER `TIPO`;

ALTER TABLE `OPERACAO`
  ADD KEY `IDX_OPERACAO_TICKET_NAVIO` (`TICKET_NAVIO`);
